name: org.quelea.mobileremote
description: An app for remote controlling the projector software Quelea.

version: 0.1.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  html: ^0.14.0+2
  preferences: ^5.2.0
  cupertino_icons: ^0.1.2
  flutter_launcher_icons: "^0.7.3"
  url_launcher: ^5.4.11
  connectivity: ^0.4.8+6
  #hardware_buttons: ^1.0.0
  ping_discover_network: ^0.2.0+1
  indexed_list_view: ^1.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/btn-logo.png
    - images/btn_next_item.png
    - images/btn_prev_item.png
    - images/btn_next_slide.png
    - images/btn_prev_slide.png
    - images/btn_record.png
    - images/btn_record_stop.png
    - images/ic_bible.png
    - images/ic_song.png
    - images/ic_theme.png
    - images/loading.gif
    - images/ic_launcher_web.png
    - images/ic_launcher.png
    - assets/chapter_lengths.txt
    - translations/en_GB.lang
    - translations/en_US.lang
    - translations/bg.lang
    - translations/chs.lang
    - translations/cs.lang
    - translations/de.lang
    - translations/es.lang
    - translations/fi.lang
    - translations/fr.lang
    - translations/hu.lang
    - translations/lt.lang
    - translations/nl.lang
    - translations/no.lang
    - translations/pj.lang
    - translations/pl.lang
    - translations/pt.lang
    - translations/pt_BR.lang
    - translations/ro.lang
    - translations/ru.lang
    - translations/sk.lang
    - translations/sv.lang
    - translations/sw.lang
    
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/ic_launcher_web.png"

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
